# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(default=None, max_length=255, verbose_name='头像'),
        ),
    ]
