# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170928_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='头像'),
        ),
    ]
